#!/usr/bin/env ruby
require 'fileutils'
require_relative 'lib/project'
require_relative 'config'

dir = File.dirname(__FILE__)
$fullDir = File.expand_path dir
$lib = dir + '/lib/'
$backupDir = dir + '/backup/'
$templateDir = dir + '/templates/'

# Log Function
class String
	def colorize(color_code)
	  "\e[#{color_code}m#{self}\e[0m"
	end
	def red; colorize(31); end
	def green; colorize(32); end
end

# Command Line Variables
action = ARGV[0]

case action
when 'create'
	name = ARGV[1]
	template = ARGV[2] ? ARGV[2] : 'default'
	project = Project.new(name)
	project.create(template)
when 'remove'
	name = ARGV[1]
	project = Project.new(name)
	project.remove
when 'export'
	if File.writable? $exportFolder
		FileUtils.ln_s $fullDir+'/webdev', $exportFolder + '/webdev'
		puts "webdev command exported".green
	else
		puts "Export folder not writable, Try again with root permissions".red
	end
when 'help'
	File.open($lib+'help.txt').each do |line|
		puts line
	end
else
	puts "An action is required, View the help by using the 'webdev help' command".red
end
	